process.env.AWS_REGION = 'us-east-1'
process.env.WORKSPACE = 'sdx'
process.env.DYNAMO_TABLE_USERS = 'users-tech-challenge-stone-sdx'
process.env.DYNAMO_TABLE_SITE_ACCESS = 'site-access-tech-challenge-stone-sdx'
process.env.DYNAMO_EVENTS_SITE_ACCESS = 'site-access-tech-challenge-stone-sdx'
